
build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "hande ercel - loans Taker"
    email: "handeimy@gmail.com"
  onCallSupport:
    - (666) 265-3765
    - (555) 734-8371