spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related qa APIs "
  contactDetails:
    name: "aliya bhatt - loans Taker"
    email: "aliya12@gmail.com"
  onCallSupport:
    - (666) 265-3765
    - (555) 734-8371